name: sbeereck_app
description: S'Beer Eck Admin App.

publish_to: 'none'

version: 0.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Firebase related stuff
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.3
  google_sign_in: ^5.1.1

  # Essentials
  provider: ^6.0.0
  routemaster: ^0.9.5
  shared_preferences: ^2.0.8
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.0.0
  mdi: ^5.0.0-nullsafety.0

  # Miscellaneous stuff
  flutter_signin_button: ^2.0.0
  package_info_plus: ^1.3.0
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/schools/
    - assets/beers/

flutter_icons:
  android: launcher_icons
  ios: false
  image_path: assets/logo.png